version: 2.1

orbs:
  codacy: codacy/base@12.2.0

workflows:
  version: 2

  compile_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
          context: CodacyAWS
      - codacy/sbt_docker:
          name: compile_and_test
          steps:
            - run:
                name: Compile
                command: sbt +test:compile
            - run:
                name: Run tests
                command: sbt +test
          use_sbt_native_client: false
          context: CodacyAWS
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: publish
          cmd: sbt "retrieveGPGKeys; +publishSigned; sonatypeCentralRelease"
          use_sbt_native_client: false
          context: CodacyAWS
          requires:
            - compile_and_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          context: CodacyAWS
          requires:
            - publish
